export const SERVICE_TYPES = {
  CREATE_WALLET: 'CREATE_WALLET',
  IMPORT_WALLET: 'IMPORT_WALLET',
  UNLOCK_WALLET: 'UNLOCK_WALLET',
  LOCK_WALLET: 'LOCK_WALLET',
  GET_WALLET_STATUS: 'GET_WALLET_STATUS',
  GET_PUBLIC_KEY: 'GET_PUBLIC_KEY',
  GET_FAILED_ATTEMPTS: 'GET_FAILED_ATTEMPTS',
  RESET_FAILED_ATTEMPTS: 'RESET_FAILED_ATTEMPTS',
  GET_NETWORKS: 'GET_NETWORKS',
  GET_ACTIVE_NETWORK: 'GET_ACTIVE_NETWORK',
  SET_ACTIVE_NETWORK: 'SET_ACTIVE_NETWORK',
  ADD_NETWORK: 'ADD_NETWORK',
  EDIT_NETWORK: 'EDIT_NETWORK',
  REMOVE_NETWORK: 'REMOVE_NETWORK',
  SIGN_AND_SUBMIT_PAYMENT: 'SIGN_AND_SUBMIT_PAYMENT',
  BUILD_PAYMENT_XDR: 'BUILD_PAYMENT_XDR',
  ADD_TRUSTLINE: 'ADD_TRUSTLINE',
  REMOVE_TRUSTLINE: 'REMOVE_TRUSTLINE',
  GET_SWAP_QUOTE: 'GET_SWAP_QUOTE',
  SIGN_AND_SUBMIT_SWAP: 'SIGN_AND_SUBMIT_SWAP',
  GET_CONNECTED_APPS: 'GET_CONNECTED_APPS',
  REVOKE_ACCESS: 'REVOKE_ACCESS',
  REVOKE_ALL_ACCESS: 'REVOKE_ALL_ACCESS',
  // Multi-account (same HD wallet)
  GET_ACCOUNTS: 'GET_ACCOUNTS',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  SWITCH_ACCOUNT: 'SWITCH_ACCOUNT',
  RENAME_ACCOUNT: 'RENAME_ACCOUNT',
  REMOVE_ACCOUNT: 'REMOVE_ACCOUNT',
  // Multi-wallet (different seed phrases / imported keys)
  CREATE_HD_WALLET: 'CREATE_HD_WALLET',
  IMPORT_HD_WALLET: 'IMPORT_HD_WALLET',
  IMPORT_SECRET_KEY: 'IMPORT_SECRET_KEY',
  REMOVE_HD_WALLET: 'REMOVE_HD_WALLET',
  REORDER_ACCOUNTS: 'REORDER_ACCOUNTS',
  // Wallet reset/wipe
  RESET_WALLET: 'RESET_WALLET',
  // Security settings
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  GET_RECOVERY_PHRASE: 'GET_RECOVERY_PHRASE',
  GET_SECRET_KEY: 'GET_SECRET_KEY',
  GET_AUTO_LOCK_TIMEOUT: 'GET_AUTO_LOCK_TIMEOUT',
  SET_AUTO_LOCK_TIMEOUT: 'SET_AUTO_LOCK_TIMEOUT',
  // Proxied network calls (routes through background to avoid popup console 404 spam)
  FETCH_HORIZON_ACCOUNT: 'FETCH_HORIZON_ACCOUNT',
  FETCH_EVM_BALANCES: 'FETCH_EVM_BALANCES',
  FETCH_BTC_BALANCES: 'FETCH_BTC_BALANCES',
  FETCH_BTC_FEES: 'FETCH_BTC_FEES',
  BTC_QUOTE: 'BTC_QUOTE',
  SIGN_AND_SUBMIT_BTC_PAYMENT: 'SIGN_AND_SUBMIT_BTC_PAYMENT',
  BTC_TX_STATUS: 'BTC_TX_STATUS',
  FETCH_BTC_ACTIVITY: 'FETCH_BTC_ACTIVITY',
  SIGN_AND_SUBMIT_EVM_PAYMENT: 'SIGN_AND_SUBMIT_EVM_PAYMENT',
  EVM_TX_STATUS: 'EVM_TX_STATUS',
  // Private mode; poolId selects the pool (optional for RECEIVE_ADDRESS). Sends, unshields and
  // retries return a review that SHIELDED_DECIDE answers.
  SHIELDED_RECEIVE_ADDRESS: 'SHIELDED_RECEIVE_ADDRESS',
  SHIELDED_STATUS: 'SHIELDED_STATUS',
  SHIELDED_SYNC: 'SHIELDED_SYNC',
  SHIELDED_SHIELD: 'SHIELDED_SHIELD',
  SHIELDED_SPEND: 'SHIELDED_SPEND',
  SHIELDED_RETRY: 'SHIELDED_RETRY',
  SHIELDED_DECIDE: 'SHIELDED_DECIDE',
  // The fee a send or unshield would pay now, and the most one payment can move with it.
  SHIELDED_QUOTE: 'SHIELDED_QUOTE',
  // The pool's deposit limits and admission delays, for the active account as the depositor.
  SHIELDED_LIMITS: 'SHIELDED_LIMITS',
  // The account takes back a pending deposit, claims a flagged deposit's refund, or claims a
  // stranded payout; id is the deposit ID or the exit ID.
  SHIELDED_CANCEL: 'SHIELDED_CANCEL',
  SHIELDED_REFUND: 'SHIELDED_REFUND',
  SHIELDED_CLAIM: 'SHIELDED_CLAIM',
  // CCTP cross-chain USDC bridge (Stellar <-> Ethereum)
  CCTP_QUOTE: 'CCTP_QUOTE',
  CCTP_START: 'CCTP_START',
  CCTP_LIST_JOBS: 'CCTP_LIST_JOBS',
  CCTP_PROCESS: 'CCTP_PROCESS',
  CCTP_RESUME: 'CCTP_RESUME',
  CCTP_CANCEL: 'CCTP_CANCEL',
  // EVM account activity (native + ERC-20 transfers) via the Cyphras indexer proxy
  FETCH_EVM_ACTIVITY: 'FETCH_EVM_ACTIVITY',
} as const

export type ServiceType = (typeof SERVICE_TYPES)[keyof typeof SERVICE_TYPES]

// For each private payment it starts, the popup holds a port named this plus a token, and sends
// the token with the request; once the port goes, the background declines that payment's reviews,
// including one that arrives later.
export const SHIELDED_REVIEW_PORT = 'shielded-review:'

export const PASSWORD_RULES = {
  MIN_LENGTH: 8,
  MAX_ATTEMPTS: 5,
  LOCKOUT_MINUTES: 15,
} as const
